#!/bin/zsh
#
# change default behaviors for the basics

. ~/.zsh/vars

alias ls='ls --color=always'
alias mc='mc -b'
alias info='clear && perl ~/info.pl'
alias pacman='yaourt'
alias mv="mv -v --backup=existing"
alias rm="rm -v"
alias cp="cp -v"
alias mplayer="mplayer -idx"
alias wget="wget --timeout 10"
alias grep="grep --color=auto"
alias reboot="sudo reboot"
alias fixres='xrandr --size 1280x800'

# auto open images
alias -s {jpg,JPG,jpeg,JPEG,png,PNG,gif,GIF}="feh -F"
 
# auto open movies
alias -s {mpg,mpeg,avi,ogm,wmv,m4v,mp4,mov}="mplayer -idx"
 
# auto open audio
alias -s {mp3,ogg,wav,flac}="mplayer"
 
# auto open web addresses
alias -s {html,php,com,net,org,gov}="firefox3"

# radia
alias radio-orion='mplayer -cache 2000 mms://82.208.50.129/ORION64'
alias radio-evropa2='mplayer -cache 200 http://netshow3.atlas.cz/evropa2-64'
alias radio-hey='mplayer -cache 200 mms://82.208.50.159/heyostrava?WMContentBitrate=130000'

#televize
alias tv-ct1='mplayer http://172.30.252.34:8080/ct1'
alias tv-ct2='mplayer http://172.30.252.34:8080/ct2'
alias tv-nova='mplayer http://172.30.252.34:8080/nova'
alias tv-ct24='mplayer http://172.30.252.34:8080/ct24'
alias tv-ct4sport='mplayer http://172.30.252.34:8080/ct4sport'
alias tv-tvp1='mplayer http://172.30.252.34:8081/tvp1'
alias tv-tvp2='mplayer http://172.30.252.34:8081/tvp2'
alias tv-tvp3='mplayer http://172.30.252.34:8081/tvp3'
alias tv-prima='mplayer http://172.25.2.201:8082'
alias tv-info='mplayer http://172.25.2.201:8083'
alias tv-pg24='mplayer mms://stream.pg24.tv/PG24-High'

# generovani hesel
alias pwd-mbank='passwordmaker -r www.mbank.cz -g 12 && echo "13124065"'
alias pwd-aukro='passwordmaker -r www.aukro.cz'
alias pwd-delicious='passwordmaker -r del.icio.us'
alias pwd-ikariam='passwordmaker -r www.ikariam.cz'
alias pwd-demonoid='passwordmaker -r www.demonoid.com'
alias pwd-trezzor='passwordmaker -r tracker.czech-server.com'
