#!/bin/zsh

# time test
function timetest() {
    time (
    for i in $(seq 1 1000); do
        php $1
    done
    )
}

# mount iso
function isomount() {
    echo "odpojuji /mnt/cdrom/"
    sudo umount /mnt/cdrom/
    echo "Pripojuji $1 do /mnt/cdrom/ ..."
    sudo mount -t iso9660 "$1" /mnt/cdrom -o loop
}

# extract files
function ex () {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xjf $1        ;;
            *.tar.gz)    tar xzf $1     ;;
            *.bz2)       bunzip2 $1       ;;
            *.rar)       rar x $1     ;;
            *.gz)        gunzip $1     ;;
            *.tar)       tar xf $1        ;;
            *.tbz2)      tar xjf $1      ;;
            *.tgz)       tar xzf $1       ;;
            *.zip)       unzip $1     ;;
            *.Z)         uncompress $1  ;;
            *.7z)        7z x $1    ;;
            *)           echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}
